version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y remove openjdk-11-jre-headless openjdk-11-jre openjdk-11-jdk-headless openjdk-11-jdk
      - apt-cache search ^openjdk
      - apt-get install openjdk-9-jdk -y
      - apt-get -y install openjdk-8-jdk-headless
      - apt-get -y install openjdk-8-jre
      - apt-get -y install openjdk-8-jre-headless
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
