version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get install mercurial -y
      - mkdir ~/openJDK9SourceCode
      - cd /openJDK9SourceCode
      - hg clone http://hg.openjdk.java.net/jdk9/dev 9dev
      - cd 9dev
      - chmod +x ./get_source.sh
      - sh ./get_source.sh
      - apt-get install openjdk-8-jdk-headless -y
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
