version: 0.2

phases:
  build:
    commands:
      - update-java-alternatives -l
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
