version: 0.2

phases:
  build:
    commands:
      - echo 'deb http://archive.ubuntu.com/ubuntu bionic-updates universe' >> /etc/apt/sources.list
      - apt-get update
      - apt-get install openjdk-9-jdk-headless -y
      - apt-get install openjdk-9-jdk -y
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
