version: 0.2

phases:
  build:
    commands:
      - hg clone http://hg.openjdk.java.net/jdk9/jdk9
      - cd ./jdk9
      - chmod +x ./get_source.sh
      - sh ./get_source.sh
      - chmod +x ./configure
      - sh ./configure --disable-warnings-as-errors --with-debug-level=slowdebug --with-native-debug-symbols=internal
      - make images
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
