version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y install libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libcups2-dev libasound2-dev
      - pwd
      - hg clone http://hg.openjdk.java.net/jdk9/jdk9
      - cd ./jdk9
      - chmod +x ./get_source.sh
      - sh ./get_source.sh
      - chmod +x ./configure
      - sh ./configure --disable-warnings-as-errors --with-debug-level=slowdebug --with-native-debug-symbols=internal
      - make images
      - ls -l
      - ls ./build
      - cd ./build/linux-x86_64-normal-server-slowdebug/images/jdk
      - echo $JAVA_HOME
      - echo "JAVA_HOME=/codebuild/output/src924109731/src/jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/" >> /etc/environment
      - source /etc/environment
      - echo $JAVA_HOME
      - java -version
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
